### ISSUE TITLE
Spanish translation is not displayed

### ISSUE THREAD

**Issue by sacbegg** [SimoneMontalto/movie-tracker-localization#4]
Apparently there is a problem with the Spanish language detection, I attach images to show how it looks like. I think the name of the variable is shown but not its translation, is it something I forgot to change in the files?

[Examples IMG](https://imgur.com/a/x8sAjxt)

**Comment by SimoneMontalto** [comment]
Thanks for the report. I accidentally deleted a ";" from the Spanish file before uploading the update to the App Store. I am in the process of releasing a fix.

**Comment by SimoneMontalto** [comment]
Fixed
